// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbA6WXwU4gXUea5lIS7WBCPZQkR2XJe40',
    appId: '1:567531068468:web:4425fd4856de441f247e61',
    messagingSenderId: '567531068468',
    projectId: 'calendardb-2cf0c',
    authDomain: 'calendardb-2cf0c.firebaseapp.com',
    storageBucket: 'calendardb-2cf0c.appspot.com',
    measurementId: 'G-D31KM7BRWC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2i8hbsgqFNxF7s4peqjGOZr7FCwVFYfY',
    appId: '1:567531068468:android:99bc01ff0ded8d1b247e61',
    messagingSenderId: '567531068468',
    projectId: 'calendardb-2cf0c',
    storageBucket: 'calendardb-2cf0c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGMmvtN3bZGSGR2YQB23BM6DGfyFCmxWo',
    appId: '1:567531068468:ios:5e8dbfa6c9822491247e61',
    messagingSenderId: '567531068468',
    projectId: 'calendardb-2cf0c',
    storageBucket: 'calendardb-2cf0c.appspot.com',
    iosBundleId: 'com.example.customCalanderapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGMmvtN3bZGSGR2YQB23BM6DGfyFCmxWo',
    appId: '1:567531068468:ios:5e8dbfa6c9822491247e61',
    messagingSenderId: '567531068468',
    projectId: 'calendardb-2cf0c',
    storageBucket: 'calendardb-2cf0c.appspot.com',
    iosBundleId: 'com.example.customCalanderapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbA6WXwU4gXUea5lIS7WBCPZQkR2XJe40',
    appId: '1:567531068468:web:76524723abca277d247e61',
    messagingSenderId: '567531068468',
    projectId: 'calendardb-2cf0c',
    authDomain: 'calendardb-2cf0c.firebaseapp.com',
    storageBucket: 'calendardb-2cf0c.appspot.com',
    measurementId: 'G-HY8Y7NQEMB',
  );
}
